### ISSUE TITLE
Register Http Object Store

### ISSUE THREAD

**Issue by mesejo** [letsql/letsql#48]
To register remote files like http, we need to add the HTTP object store, basically with the following steps:

Add the feature in the Cargo.toml

```toml
object_store = { version = "0.9.0", features = ["aws", "gcp", "http"] }
```

Then add the store.rs from arrow-datafusion-python

https://github.com/apache/datafusion-python/blob/main/src/store.rs

Then finally register a Http store

**Comment by dlovell** [comment]
@mesejo I think that only `datafusion-cli` has the ability to use external `http`/`https` tables
https://datafusion.apache.org/user-guide/cli/datasources.html#http-s
